dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: instance
  image: ${DOCKER_IMAGE}
  pre_build_image: yes
  privileged: true
  command: /usr/lib/systemd/systemd --system
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  tty: false
  environment:
    container: docker
  volume:
  - /sys/fs/cgroup
  groups:
  - docker
provisioner:
  name: ansible
  options:
    vvv: false
  log: false
verifier:
  name: ansible
lint: |-
  set -e
  yamllint .
  ansible-lint
